BEGIN TRANSACTION;
DROP TABLE IF EXISTS "pays";
CREATE TABLE IF NOT EXISTS "pays" (
	"id_pays"	TEXT PRIMARY KEY,
	"nom_pays"	TEXT
);
INSERT INTO "pays" ("id_pays","nom_pays") VALUES ('ab','Ecosse'),
 ('ae','Emirats Arabes Unis'),
 ('ar','Argentine'),
 ('at','Autriche'),
 ('au','Australie'),
 ('bd','Bangladesh'),
 ('be','Belgique'),
 ('bn','Brunei'),
 ('br','Bresil'),
 ('ca','Canada'),
 ('cl','Chili'),
 ('de','Allemagne'),
 ('dk','Danemark'),
 ('dz','Algerie'),
 ('eg','Egypte'),
 ('en','Angleterre'),
 ('es','Espagne'),
 ('fi','Finlande'),
 ('fr','France'),
 ('gb','Royaume Uni'),
 ('id','Indonesie'),
 ('ie','Irlande'),
 ('in','Inde'),
 ('it','Italie'),
 ('jo','Jordanie'),
 ('jp','Japon'),
 ('kh','Cambodge'),
 ('kr','Coree du Sud'),
 ('kw','Koweit'),
 ('la','Laos'),
 ('lt','lituanie'),
 ('ly','Libye'),
 ('ma','Maroc'),
 ('mn','Mongolie'),
 ('mv','Maldives'),
 ('mx','Mexique'),
 ('my','Malaisie'),
 ('nl','Pays Bas'),
 ('no','Norvege'),
 ('nz','Nouvelle-Zelande'),
 ('om','Oman'),
 ('ph','Philippines'),
 ('pl','Pologne'),
 ('pr','Puerto Rico'),
 ('pt','Portugal'),
 ('qa','Qatar'),
 ('re','Reunion'),
 ('sa','Arabie Saoudite'),
 ('se','Suede'),
 ('sg','Singapour'),
 ('si','Slovenie'),
 ('th','Thailande'),
 ('tn','Tunisie'),
 ('tr','Turquie'),
 ('us','Etats Unis'),
 ('uy','Uruguay'),
 ('vn','Vietnam'),
 ('wl','Sainte Lucie'),
 ('ye','Yemen'),
 ('za','Afrique du Sud'),
 ('na','Namibie');
COMMIT;
